Upgrade WIP 3 – Upgrade metalsmith-templates to see if it fixes error
The plugin is deprecated, but I'm already changing too many things for
migrating away from it, too.

The error was:

```
/Users/gio/Developer/mokagio/mokacoding.com/node_modules/metalsmith-templates/lib/index.js:78
        str = metalsmith.join(dir, data.template || def);
                         ^

TypeError: metalsmith.join is not a function
    at convert (/Users/gio/Developer/mokagio/mokacoding.com/node_modules/metalsmith-templates/lib/index.js:78:26)
    at /Users/gio/Developer/mokagio/mokacoding.com/node_modules/async/lib/async.js:111:13
    at Array.forEach (<anonymous>)
    at _each (/Users/gio/Developer/mokagio/mokacoding.com/node_modules/async/lib/async.js:32:24)
    at async.each (/Users/gio/Developer/mokagio/mokacoding.com/node_modules/async/lib/async.js:110:9)
    at /Users/gio/Developer/mokagio/mokacoding.com/node_modules/metalsmith-templates/lib/index.js:64:5
    at Timeout.next [as _onTimeout] (/Users/gio/Developer/mokagio/mokacoding.com/node_modules/ware/lib/index.js:68:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```